# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris(object):
    def setupUi(self, Giris):
        Giris.setObjectName("Giris")
        Giris.resize(400, 300)
        self.girisbutonu = QtWidgets.QPushButton(Giris)
        self.girisbutonu.setGeometry(QtCore.QRect(150, 150, 93, 28))
        self.girisbutonu.setObjectName("girisbutonu")
        self.epostalabel = QtWidgets.QLabel(Giris)
        self.epostalabel.setGeometry(QtCore.QRect(50, 30, 55, 16))
        self.epostalabel.setObjectName("epostalabel")
        self.sifrelabel = QtWidgets.QLabel(Giris)
        self.sifrelabel.setGeometry(QtCore.QRect(50, 70, 55, 16))
        self.sifrelabel.setObjectName("sifrelabel")
        self.mesajlabel = QtWidgets.QLabel(Giris)
        self.mesajlabel.setGeometry(QtCore.QRect(100, 200, 231, 20))
        self.mesajlabel.setObjectName("mesajlabel")
        self.epostaText = QtWidgets.QLineEdit(Giris)
        self.epostaText.setGeometry(QtCore.QRect(140, 30, 113, 22))
        self.epostaText.setObjectName("epostaText")
        self.sifreText = QtWidgets.QLineEdit(Giris)
        self.sifreText.setGeometry(QtCore.QRect(140, 70, 113, 22))
        self.sifreText.setObjectName("sifreText")

        self.retranslateUi(Giris)
        QtCore.QMetaObject.connectSlotsByName(Giris)

    def retranslateUi(self, Giris):
        _translate = QtCore.QCoreApplication.translate
        Giris.setWindowTitle(_translate("Giris", "Form"))
        self.girisbutonu.setText(_translate("Giris", "Giriş"))
        self.epostalabel.setText(_translate("Giris", "Eposta:"))
        self.sifrelabel.setText(_translate("Giris", "Sifre:"))
        self.mesajlabel.setText(_translate("Giris", "                   Mesaj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Giris = QtWidgets.QWidget()
    ui = Ui_Giris()
    ui.setupUi(Giris)
    Giris.show()
    sys.exit(app.exec_())
