# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KitapEkle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KitapEkleForm(object):
    def setupUi(self, KitapEkleForm):
        KitapEkleForm.setObjectName("KitapEkleForm")
        KitapEkleForm.resize(400, 300)
        KitapEkleForm.setMinimumSize(QtCore.QSize(100, 10))
        self.formLayoutWidget = QtWidgets.QWidget(KitapEkleForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 30, 178, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.kitapAdiLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitapAdiLabel.setObjectName("kitapAdiLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kitapAdiLabel)
        self.KitapAdi = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.KitapAdi.setObjectName("KitapAdi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.KitapAdi)
        self.kitapYazarLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitapYazarLabel.setObjectName("kitapYazarLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kitapYazarLabel)
        self.kitapYazarLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.kitapYazarLineEdit.setObjectName("kitapYazarLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kitapYazarLineEdit)
        self.okunmaDurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.okunmaDurumuLabel.setObjectName("okunmaDurumuLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.okunmaDurumuLabel)
        self.okunmaDurumuCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.okunmaDurumuCheckBox.setObjectName("okunmaDurumuCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.okunmaDurumuCheckBox)
        self.begeniDurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.begeniDurumuLabel.setObjectName("begeniDurumuLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.begeniDurumuLabel)
        self.begeniDurumuComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.begeniDurumuComboBox.setObjectName("begeniDurumuComboBox")
        self.begeniDurumuComboBox.addItem("")
        self.begeniDurumuComboBox.addItem("")
        self.begeniDurumuComboBox.addItem("")
        self.begeniDurumuComboBox.addItem("")
        self.begeniDurumuComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.begeniDurumuComboBox)
        self.kayitDurumLabel = QtWidgets.QLabel(KitapEkleForm)
        self.kayitDurumLabel.setGeometry(QtCore.QRect(120, 190, 171, 20))
        self.kayitDurumLabel.setObjectName("kayitDurumLabel")
        self.kitapkaydetbutonu = QtWidgets.QPushButton(KitapEkleForm)
        self.kitapkaydetbutonu.setGeometry(QtCore.QRect(120, 230, 93, 28))
        self.kitapkaydetbutonu.setObjectName("kitapkaydetbutonu")

        self.retranslateUi(KitapEkleForm)
        QtCore.QMetaObject.connectSlotsByName(KitapEkleForm)

    def retranslateUi(self, KitapEkleForm):
        _translate = QtCore.QCoreApplication.translate
        KitapEkleForm.setWindowTitle(_translate("KitapEkleForm", "Form"))
        self.kitapAdiLabel.setText(_translate("KitapEkleForm", "Kitap Adı"))
        self.kitapYazarLabel.setText(_translate("KitapEkleForm", "Kitap Yazarı"))
        self.okunmaDurumuLabel.setText(_translate("KitapEkleForm", "Okunma Durumu"))
        self.begeniDurumuLabel.setText(_translate("KitapEkleForm", "Beğeni Durumu"))
        self.begeniDurumuComboBox.setItemText(0, _translate("KitapEkleForm", "1"))
        self.begeniDurumuComboBox.setItemText(1, _translate("KitapEkleForm", "2"))
        self.begeniDurumuComboBox.setItemText(2, _translate("KitapEkleForm", "3"))
        self.begeniDurumuComboBox.setItemText(3, _translate("KitapEkleForm", "4"))
        self.begeniDurumuComboBox.setItemText(4, _translate("KitapEkleForm", "5"))
        self.kayitDurumLabel.setText(_translate("KitapEkleForm", "Kayıt  Durumu"))
        self.kitapkaydetbutonu.setText(_translate("KitapEkleForm", "Kitap Kaydet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KitapEkleForm = QtWidgets.QWidget()
    ui = Ui_KitapEkleForm()
    ui.setupUi(KitapEkleForm)
    KitapEkleForm.show()
    sys.exit(app.exec_())
